INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('J K K Munirajah College of Technology', 'Erode', 'Non-Autonomous', 146.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Nandha College of Technology', 'Erode', 'Autonomous', 153);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Surya Engineering College', 'Erode', 'Non-Autonomous', 140.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Shree Venkateshwara Hi-Tech Engineering College', 'Erode', 'Non-Autonomous', 135.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Erode Builder Educational Trusts Group of Institutions', 'Tiruppur', 'Autonomous', 181.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('M P Nachimuthu M Jaganathan Engineering College', 'Erode', 'Non-Autonomous', 147);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Aishwarya College of Engineering and Technology', 'Erode', 'Non-Autonomous', 153.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vidhya Mandhir Institute of Technology', 'Erode', 'Non-Autonomous', 144);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Erode Sengunthar Engineering College', 'Erode', 'Autonomous', 172);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Al-Ameen Engineering College', 'Erode', 'Non-Autonomous', 144.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('University Departments of Anna University, Chennai - CEG Campus', 'Chennai', 'Non-Autonomous', 199.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('University Departments of Anna University, Chennai - ACT Campus', 'Chennai', 'Non-Autonomous', 197.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Central Institute of Plastics Engineering and Technology', 'Chennai', 'Non-Autonomous', 190.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Loyola - ICAM College of Engineering and Technology', 'Chennai', 'Non-Autonomous', 192.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Meenakshi College of Engineering', 'Chennai', 'Non-Autonomous', 182.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Government College of Technology (GCT)', 'Coimbatore', 'Non-Autonomous', 197.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('PSG College of Technology', 'Coimbatore', 'Non-Autonomous', 199);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Coimbatore Institute of Technology (CIT)', 'Coimbatore', 'Non-Autonomous', 198);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr Mahalingam College of Engineering & Technology', 'Coimbatore', 'Non-Autonomous', 192.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Thiagarajar College of Engineering', 'Madurai', 'Non-Autonomous', 198);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Velammal College of Engineering and Technology', 'Madurai', 'Non-Autonomous', 191.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('University College of Engineering, Tiruchirappalli', 'Tiruchirappalli', 'Non-Autonomous', 192.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('J J College of Engineering and Technology', 'Tiruchirappalli', 'Non-Autonomous', 170.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Government College of Engineering - Salem', 'Salem', 'Non-Autonomous', 196);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sona College of Technology', 'Salem', 'Autonomous', 192.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('The Kavery Engineering College', 'Salem', 'Non-Autonomous', 161.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Knowledge Institute of Technology', 'Salem', 'Non-Autonomous', 174.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Annapoorana Engineering College', 'Salem', 'Non-Autonomous', 113.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Tagore Institute of Engineering and Technology', 'Salem', 'Non-Autonomous', 125);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Greentech College of Engineering for Women', 'Salem', 'Non-Autonomous', 130.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sree Krishna College of Engineering', 'Vellore', 'Non-Autonomous', 108.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Adhiparasakthi College of Engineering', 'Vellore', 'Non-Autonomous', 159.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('C Abdul Hakeem College of Engineering and Technology', 'Vellore', 'Non-Autonomous', 175);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Priyadarshini Engineering College', 'Vellore', 'Non-Autonomous', 158.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Ranippettai Engineering College', 'Vellore', 'Non-Autonomous', 129.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Nandhanam College of Engineering and Technology', 'Vellore', 'Non-Autonomous', 141.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Saraswathi Velu College of Engineering', 'Vellore', 'Non-Autonomous', 116.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('University College of Engineering, Nagercoil', 'Kanniyakumari', 'Non-Autonomous', 189.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maria College of Engineering and Technology', 'Kanniyakumari', 'Non-Autonomous', 141.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mar Ephraem College of Engineering and Technology', 'Kanniyakumari', 'Non-Autonomous', 135);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sivaji College of Engineering and Technology', 'Kanniyakumari', 'Non-Autonomous', 118.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Satyam College of Engineering and Technology', 'Kanniyakumari', 'Non-Autonomous', 106.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Arunachala College of Engineering for Women', 'Kanniyakumari', 'Non-Autonomous', 157);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vins Christian Women''s College of Engineering', 'Kanniyakumari', 'Non-Autonomous', 146.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Stella Mary''s College of Engineering', 'Kanniyakumari', 'Non-Autonomous', 153.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('University College of Engineering, Pattukkottai', 'Thanjavur', 'Non-Autonomous', 178.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SMR East Coast College of Engineering and Technology', 'Thanjavur', 'Non-Autonomous', 127.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Star Lion College of Engineering and Technology', 'Thanjavur', 'Non-Autonomous', 96.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Arasu Engineering College', 'Thanjavur', 'Non-Autonomous', 156);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('P.R. Engineering College', 'Thanjavur', 'Non-Autonomous', 134.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Ponnaiyah Ramajayam College of Engineering and Technology', 'Thanjavur', 'Non-Autonomous', 137.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('St. Joseph''s College of Engineering and Technology', 'Thanjavur', 'Non-Autonomous', 138);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Parisutham Institute of Technology and Science', 'Thanjavur', 'Non-Autonomous', 168);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vandayar Engineering College', 'Thanjavur', 'Non-Autonomous', 120);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Annai College of Engineering and Technology', 'Thanjavur', 'Non-Autonomous', 120.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Thamirabharani Engineering College', 'Tirunelveli', 'Non-Autonomous', 111);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SCAD Engineering College', 'Tirunelveli', 'Non-Autonomous', 133);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('A R College of Engineering and Technology', 'Tirunelveli', 'Non-Autonomous', 112.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Arul College of Technology', 'Tirunelveli', 'Non-Autonomous', 99.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Cape Institute of Technology', 'Tirunelveli', 'Non-Autonomous', 155.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Francis Xavier Engineering College', 'Tirunelveli', 'Non-Autonomous', 171.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Joe Suresh Engineering College', 'Tirunelveli', 'Non-Autonomous', 108);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National College of Engineering', 'Tirunelveli', 'Non-Autonomous', 164.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('PSN College of Engineering and Technology', 'Tirunelveli', 'Non-Autonomous', 158.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('PET Engineering College', 'Tirunelveli', 'Non-Autonomous', 158.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('University Departments of Anna University, Chennai - MIT Campus', 'Kanchipuram', 'Non-Autonomous', 198.67);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('University College of Engineering, Kanchipuram', 'Kanchipuram', 'Non-Autonomous', 186.25);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Arignar Anna Institute of Science and Technology', 'Kanchipuram', 'Non-Autonomous', 147.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('D M I College of Engineering', 'Kanchipuram', 'Non-Autonomous', 162);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalsar College of Engineering', 'Kanchipuram', 'Non-Autonomous', 132);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Lord Venkateshwaraa Engineering College', 'Kanchipuram', 'Non-Autonomous', 176.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maamallan Institute of Technology', 'Kanchipuram', 'Non-Autonomous', 179.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pallavan College of Engineering', 'Kanchipuram', 'Non-Autonomous', 168.75);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('P B College of Engineering', 'Kanchipuram', 'Non-Autonomous', 167);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Prince Shri Venkateshwara Padmavathy Engineering College', 'Kanchipuram', 'Non-Autonomous', 188.5);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City Institute of Science and Technology of Ariyalur', 'Ariyalur', 'Government', 114.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City Institute of Science and Technology of Ariyalur', 'Ariyalur', 'Non-Autonomous', 145.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj City Institute of Technology of Ariyalur', 'Ariyalur', 'Autonomous', 156.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha Engineering College of Ariyalur', 'Ariyalur', 'Non-Autonomous', 122.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha Institute of Science and Technology of Ariyalur', 'Ariyalur', 'Autonomous', 170.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Regional Institute of Technology of Ariyalur', 'Ariyalur', 'Non-Autonomous', 145.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha College of Engineering of Ariyalur', 'Ariyalur', 'Non-Autonomous', 178.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar City Institute of Technology of Ariyalur', 'Ariyalur', 'Autonomous', 191.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer Regional College of Engineering of Ariyalur', 'Ariyalur', 'Autonomous', 129.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer City Engineering College of Ariyalur', 'Ariyalur', 'Non-Autonomous', 167.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa College of Engineering of Ariyalur', 'Ariyalur', 'Non-Autonomous', 176.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS College of Engineering of Chengalpattu', 'Chengalpattu', 'Non-Autonomous', 103.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer City College of Engineering of Chengalpattu', 'Chengalpattu', 'Non-Autonomous', 159.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha Regional College of Engineering of Chengalpattu', 'Chengalpattu', 'Non-Autonomous', 148.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City College of Engineering of Chengalpattu', 'Chengalpattu', 'Government-Aided', 174.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Institute of Science and Technology of Chengalpattu', 'Chengalpattu', 'Non-Autonomous', 114.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna City Institute of Technology of Chengalpattu', 'Chengalpattu', 'Non-Autonomous', 95.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar City Engineering College of Chengalpattu', 'Chengalpattu', 'Non-Autonomous', 132.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS Institute of Science and Technology of Chengalpattu', 'Chengalpattu', 'Non-Autonomous', 94.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS City Institute of Technology of Chengalpattu', 'Chengalpattu', 'Autonomous', 172.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Regional College of Engineering of Chengalpattu', 'Chengalpattu', 'Autonomous', 182.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Engineering College of Chengalpattu', 'Chengalpattu', 'Non-Autonomous', 111.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna Engineering College of Chennai', 'Chennai', 'Non-Autonomous', 163.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam College of Engineering of Chennai', 'Chennai', 'Non-Autonomous', 183.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha Regional Institute of Science and Technology of Chennai', 'Chennai', 'Autonomous', 102.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj Regional Institute of Technology of Chennai', 'Chennai', 'Non-Autonomous', 165.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar Regional Institute of Technology of Chennai', 'Chennai', 'Non-Autonomous', 124.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Regional College of Engineering of Chennai', 'Chennai', 'Autonomous', 164.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National Institute of Technology of Chennai', 'Chennai', 'Non-Autonomous', 110.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Institute of Science and Technology of Chennai', 'Chennai', 'Non-Autonomous', 111.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS College of Engineering of Chennai', 'Chennai', 'Government-Aided', 91.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj City Institute of Technology of Chennai', 'Chennai', 'Non-Autonomous', 110.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj Regional Institute of Science and Technology of Coimbatore', 'Coimbatore', 'Non-Autonomous', 135.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar Regional Institute of Science and Technology of Coimbatore', 'Coimbatore', 'Autonomous', 141.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal City Institute of Technology of Coimbatore', 'Coimbatore', 'Non-Autonomous', 131.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Regional Institute of Technology of Coimbatore', 'Coimbatore', 'Non-Autonomous', 174.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar City Institute of Science and Technology of Coimbatore', 'Coimbatore', 'Non-Autonomous', 98.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer Regional Engineering College of Coimbatore', 'Coimbatore', 'Autonomous', 178.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha City Engineering College of Coimbatore', 'Coimbatore', 'Autonomous', 115.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Regional Engineering College of Coimbatore', 'Coimbatore', 'Government', 129.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Engineering College of Coimbatore', 'Coimbatore', 'Autonomous', 125.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Institute of Science and Technology of Coimbatore', 'Coimbatore', 'Autonomous', 98.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Institute of Science and Technology of Coimbatore', 'Coimbatore', 'Non-Autonomous', 111.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer Regional Institute of Science and Technology of Coimbatore', 'Coimbatore', 'Autonomous', 198.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Institute of Technology of Coimbatore', 'Coimbatore', 'Autonomous', 120.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna City Institute of Technology of Coimbatore', 'Coimbatore', 'Non-Autonomous', 189.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS Engineering College of Coimbatore', 'Coimbatore', 'Non-Autonomous', 107.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel Regional Engineering College of Cuddalore', 'Cuddalore', 'Non-Autonomous', 153.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar Regional Institute of Science and Technology of Cuddalore', 'Cuddalore', 'Non-Autonomous', 157.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Regional Engineering College of Cuddalore', 'Cuddalore', 'Non-Autonomous', 158.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj Institute of Science and Technology of Cuddalore', 'Cuddalore', 'Non-Autonomous', 112.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri City Engineering College of Cuddalore', 'Cuddalore', 'Non-Autonomous', 103.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa City Institute of Science and Technology of Cuddalore', 'Cuddalore', 'Autonomous', 112.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Institute of Science and Technology of Cuddalore', 'Cuddalore', 'Non-Autonomous', 123.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa City Institute of Science and Technology of Cuddalore', 'Cuddalore', 'Non-Autonomous', 193.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Institute of Science and Technology of Cuddalore', 'Cuddalore', 'Autonomous', 92.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Institute of Technology of Cuddalore', 'Cuddalore', 'Non-Autonomous', 153.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna City Engineering College of Cuddalore', 'Cuddalore', 'Non-Autonomous', 132.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam College of Engineering of Cuddalore', 'Cuddalore', 'Autonomous', 141.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Regional College of Engineering of Cuddalore', 'Cuddalore', 'Autonomous', 144.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City Institute of Science and Technology of Cuddalore', 'Cuddalore', 'Autonomous', 149.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal City College of Engineering of Cuddalore', 'Cuddalore', 'Autonomous', 173.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa Regional Institute of Science and Technology of Dharmapuri', 'Dharmapuri', 'Non-Autonomous', 149.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel Engineering College of Dharmapuri', 'Dharmapuri', 'Non-Autonomous', 174.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS Regional Institute of Technology of Dharmapuri', 'Dharmapuri', 'Autonomous', 162.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Engineering College of Dharmapuri', 'Dharmapuri', 'Non-Autonomous', 95.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Regional Institute of Science and Technology of Dharmapuri', 'Dharmapuri', 'Non-Autonomous', 91.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National City Institute of Technology of Dharmapuri', 'Dharmapuri', 'Autonomous', 189.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna Engineering College of Dharmapuri', 'Dharmapuri', 'Non-Autonomous', 112.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS Regional Engineering College of Dharmapuri', 'Dharmapuri', 'Non-Autonomous', 179.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City Institute of Science and Technology of Dharmapuri', 'Dharmapuri', 'Non-Autonomous', 94.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri City Institute of Science and Technology of Dharmapuri', 'Dharmapuri', 'Non-Autonomous', 102.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha Regional Institute of Technology of Dindigul', 'Dindigul', 'Autonomous', 112.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Institute of Science and Technology of Dindigul', 'Dindigul', 'Non-Autonomous', 116.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Engineering College of Dindigul', 'Dindigul', 'Autonomous', 133.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj Regional Institute of Technology of Dindigul', 'Dindigul', 'Non-Autonomous', 199.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel Regional Institute of Technology of Dindigul', 'Dindigul', 'Non-Autonomous', 134.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer City Institute of Science and Technology of Dindigul', 'Dindigul', 'Non-Autonomous', 164.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna City Engineering College of Dindigul', 'Dindigul', 'Government-Aided', 131.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Institute of Science and Technology of Dindigul', 'Dindigul', 'Autonomous', 177.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha City Institute of Technology of Dindigul', 'Dindigul', 'Non-Autonomous', 99.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Institute of Science and Technology of Dindigul', 'Dindigul', 'Autonomous', 127.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City Engineering College of Dindigul', 'Dindigul', 'Non-Autonomous', 95.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Institute of Technology of Dindigul', 'Dindigul', 'Non-Autonomous', 133.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Institute of Science and Technology of Dindigul', 'Dindigul', 'Non-Autonomous', 116.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Institute of Science and Technology of Dindigul', 'Dindigul', 'Non-Autonomous', 140.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj Engineering College of Erode', 'Erode', 'Non-Autonomous', 165.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS Regional College of Engineering of Erode', 'Erode', 'Autonomous', 132.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar Regional Institute of Technology of Erode', 'Erode', 'Non-Autonomous', 147.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Engineering College of Erode', 'Erode', 'Autonomous', 114.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Regional Institute of Science and Technology of Erode', 'Erode', 'Non-Autonomous', 171.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National City Institute of Science and Technology of Erode', 'Erode', 'Non-Autonomous', 102.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS City Engineering College of Erode', 'Erode', 'Non-Autonomous', 165.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Institute of Science and Technology of Erode', 'Erode', 'Government-Aided', 181.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar City Engineering College of Erode', 'Erode', 'Autonomous', 177.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Regional College of Engineering of Erode', 'Erode', 'Autonomous', 158.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Engineering College of Erode', 'Erode', 'Non-Autonomous', 138.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City College of Engineering of Erode', 'Erode', 'Non-Autonomous', 134.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global City Institute of Technology of Erode', 'Erode', 'Non-Autonomous', 151.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa City Engineering College of Erode', 'Erode', 'Non-Autonomous', 158.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha College of Engineering of Erode', 'Erode', 'Non-Autonomous', 92.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna Institute of Science and Technology of Kallakurichi', 'Kallakurichi', 'Non-Autonomous', 95.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National Engineering College of Kallakurichi', 'Kallakurichi', 'Autonomous', 95.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Regional College of Engineering of Kallakurichi', 'Kallakurichi', 'Non-Autonomous', 148.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam City College of Engineering of Kallakurichi', 'Kallakurichi', 'Non-Autonomous', 136.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Institute of Technology of Kallakurichi', 'Kallakurichi', 'Non-Autonomous', 170.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar Engineering College of Kallakurichi', 'Kallakurichi', 'Non-Autonomous', 177.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City College of Engineering of Kallakurichi', 'Kallakurichi', 'Non-Autonomous', 111.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel Regional Institute of Science and Technology of Kallakurichi', 'Kallakurichi', 'Government', 125.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Institute of Technology of Kallakurichi', 'Kallakurichi', 'Non-Autonomous', 158.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Engineering College of Kallakurichi', 'Kallakurichi', 'Non-Autonomous', 103.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS Engineering College of Kallakurichi', 'Kallakurichi', 'Non-Autonomous', 175.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Regional Engineering College of Kallakurichi', 'Kallakurichi', 'Non-Autonomous', 173.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS Regional Institute of Science and Technology of Kanchipuram', 'Kanchipuram', 'Non-Autonomous', 141.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global Institute of Science and Technology of Kanchipuram', 'Kanchipuram', 'Autonomous', 160.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna City Institute of Technology of Kanchipuram', 'Kanchipuram', 'Non-Autonomous', 129.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Engineering College of Kanchipuram', 'Kanchipuram', 'Non-Autonomous', 175.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Institute of Technology of Kanchipuram', 'Kanchipuram', 'Autonomous', 153.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Regional Institute of Technology of Kanchipuram', 'Kanchipuram', 'Non-Autonomous', 192.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Regional Engineering College of Kanchipuram', 'Kanchipuram', 'Autonomous', 127.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City College of Engineering of Kanchipuram', 'Kanchipuram', 'Non-Autonomous', 152.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Institute of Science and Technology of Kanchipuram', 'Kanchipuram', 'Non-Autonomous', 154.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS Regional College of Engineering of Kanchipuram', 'Kanchipuram', 'Government', 102.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Engineering College of Kanchipuram', 'Kanchipuram', 'Non-Autonomous', 136.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS Institute of Technology of Kanchipuram', 'Kanchipuram', 'Government', 174.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri City Engineering College of Kanchipuram', 'Kanchipuram', 'Non-Autonomous', 125.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha City Institute of Technology of Kanchipuram', 'Kanchipuram', 'Non-Autonomous', 91.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Institute of Technology of Kanyakumari', 'Kanyakumari', 'Autonomous', 134.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Regional Engineering College of Kanyakumari', 'Kanyakumari', 'Government', 119.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer Engineering College of Kanyakumari', 'Kanyakumari', 'Non-Autonomous', 193.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel College of Engineering of Kanyakumari', 'Kanyakumari', 'Non-Autonomous', 187.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan Institute of Technology of Kanyakumari', 'Kanyakumari', 'Non-Autonomous', 160.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Engineering College of Kanyakumari', 'Kanyakumari', 'Non-Autonomous', 126.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam Institute of Science and Technology of Kanyakumari', 'Kanyakumari', 'Non-Autonomous', 144.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita City Institute of Technology of Kanyakumari', 'Kanyakumari', 'Non-Autonomous', 142.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer City Engineering College of Kanyakumari', 'Kanyakumari', 'Non-Autonomous', 93.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Institute of Science and Technology of Kanyakumari', 'Kanyakumari', 'Non-Autonomous', 124.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global City Institute of Science and Technology of Kanyakumari', 'Kanyakumari', 'Non-Autonomous', 171.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna Regional Engineering College of Kanyakumari', 'Kanyakumari', 'Non-Autonomous', 165.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Engineering College of Kanyakumari', 'Kanyakumari', 'Non-Autonomous', 167.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Institute of Science and Technology of Kanyakumari', 'Kanyakumari', 'Autonomous', 125.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar City Engineering College of Karur', 'Karur', 'Non-Autonomous', 188.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global Institute of Technology of Karur', 'Karur', 'Autonomous', 129.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam Institute of Science and Technology of Karur', 'Karur', 'Non-Autonomous', 124.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Institute of Technology of Karur', 'Karur', 'Government-Aided', 119.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna Regional Institute of Technology of Karur', 'Karur', 'Non-Autonomous', 188.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer City Engineering College of Karur', 'Karur', 'Non-Autonomous', 92.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Engineering College of Karur', 'Karur', 'Non-Autonomous', 122.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa College of Engineering of Karur', 'Karur', 'Non-Autonomous', 152.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar College of Engineering of Karur', 'Karur', 'Autonomous', 168.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National College of Engineering of Karur', 'Karur', 'Autonomous', 122.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Institute of Technology of Karur', 'Karur', 'Autonomous', 149.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Regional College of Engineering of Krishnagiri', 'Krishnagiri', 'Government', 182.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Engineering College of Krishnagiri', 'Krishnagiri', 'Government-Aided', 197.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar City Engineering College of Krishnagiri', 'Krishnagiri', 'Non-Autonomous', 184.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Institute of Technology of Krishnagiri', 'Krishnagiri', 'Non-Autonomous', 184.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna City Institute of Science and Technology of Krishnagiri', 'Krishnagiri', 'Non-Autonomous', 144.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa Institute of Technology of Krishnagiri', 'Krishnagiri', 'Non-Autonomous', 126.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City College of Engineering of Krishnagiri', 'Krishnagiri', 'Non-Autonomous', 165.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Regional College of Engineering of Krishnagiri', 'Krishnagiri', 'Non-Autonomous', 164.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS College of Engineering of Krishnagiri', 'Krishnagiri', 'Autonomous', 153.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS City Engineering College of Krishnagiri', 'Krishnagiri', 'Non-Autonomous', 159.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar College of Engineering of Krishnagiri', 'Krishnagiri', 'Autonomous', 156.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Institute of Science and Technology of Krishnagiri', 'Krishnagiri', 'Non-Autonomous', 138.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global City Engineering College of Madurai', 'Madurai', 'Government-Aided', 166.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Engineering College of Madurai', 'Madurai', 'Autonomous', 91.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Regional College of Engineering of Madurai', 'Madurai', 'Non-Autonomous', 185.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa City Institute of Science and Technology of Madurai', 'Madurai', 'Non-Autonomous', 175.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj City Institute of Science and Technology of Madurai', 'Madurai', 'Non-Autonomous', 178.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar City College of Engineering of Madurai', 'Madurai', 'Non-Autonomous', 139.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Institute of Science and Technology of Madurai', 'Madurai', 'Non-Autonomous', 141.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri City Institute of Technology of Madurai', 'Madurai', 'Autonomous', 173.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa Regional Institute of Technology of Madurai', 'Madurai', 'Non-Autonomous', 160.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath City Institute of Technology of Madurai', 'Madurai', 'Non-Autonomous', 98.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Engineering College of Madurai', 'Madurai', 'Government', 91.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar City Institute of Science and Technology of Madurai', 'Madurai', 'Non-Autonomous', 161.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar Regional Institute of Science and Technology of Mayiladuthurai', 'Mayiladuthurai', 'Non-Autonomous', 174.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City Engineering College of Mayiladuthurai', 'Mayiladuthurai', 'Autonomous', 162.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer College of Engineering of Mayiladuthurai', 'Mayiladuthurai', 'Autonomous', 118.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS Institute of Science and Technology of Mayiladuthurai', 'Mayiladuthurai', 'Autonomous', 130.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal City College of Engineering of Mayiladuthurai', 'Mayiladuthurai', 'Non-Autonomous', 116.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna City College of Engineering of Mayiladuthurai', 'Mayiladuthurai', 'Non-Autonomous', 162.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar City College of Engineering of Mayiladuthurai', 'Mayiladuthurai', 'Non-Autonomous', 148.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National City Institute of Technology of Mayiladuthurai', 'Mayiladuthurai', 'Non-Autonomous', 193.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global Institute of Science and Technology of Mayiladuthurai', 'Mayiladuthurai', 'Autonomous', 112.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Regional Institute of Technology of Mayiladuthurai', 'Mayiladuthurai', 'Non-Autonomous', 194.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar Regional Institute of Science and Technology of Nagapattinam', 'Nagapattinam', 'Non-Autonomous', 188.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global Regional Engineering College of Nagapattinam', 'Nagapattinam', 'Non-Autonomous', 168.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Institute of Technology of Nagapattinam', 'Nagapattinam', 'Non-Autonomous', 192.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National City College of Engineering of Nagapattinam', 'Nagapattinam', 'Autonomous', 113.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha City Institute of Technology of Nagapattinam', 'Nagapattinam', 'Autonomous', 109.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha City Institute of Science and Technology of Nagapattinam', 'Nagapattinam', 'Government-Aided', 155.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Engineering College of Nagapattinam', 'Nagapattinam', 'Autonomous', 148.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City College of Engineering of Nagapattinam', 'Nagapattinam', 'Non-Autonomous', 100.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna Institute of Technology of Nagapattinam', 'Nagapattinam', 'Non-Autonomous', 97.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global City Engineering College of Nagapattinam', 'Nagapattinam', 'Non-Autonomous', 185.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City Engineering College of Namakkal', 'Namakkal', 'Autonomous', 158.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Regional Institute of Technology of Namakkal', 'Namakkal', 'Non-Autonomous', 189.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Regional Institute of Science and Technology of Namakkal', 'Namakkal', 'Non-Autonomous', 150.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam City College of Engineering of Namakkal', 'Namakkal', 'Autonomous', 195.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS Regional Engineering College of Namakkal', 'Namakkal', 'Non-Autonomous', 193.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Institute of Technology of Namakkal', 'Namakkal', 'Non-Autonomous', 101.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Institute of Technology of Namakkal', 'Namakkal', 'Non-Autonomous', 153.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna Regional Institute of Science and Technology of Namakkal', 'Namakkal', 'Government-Aided', 121.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS City Engineering College of Namakkal', 'Namakkal', 'Autonomous', 104.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa City College of Engineering of Namakkal', 'Namakkal', 'Non-Autonomous', 181.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Institute of Technology of Namakkal', 'Namakkal', 'Non-Autonomous', 146.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global Institute of Technology of Namakkal', 'Namakkal', 'Non-Autonomous', 152.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam City College of Engineering of Namakkal', 'Namakkal', 'Non-Autonomous', 175.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City Engineering College of Namakkal', 'Namakkal', 'Autonomous', 159.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath City Institute of Technology of Nilgiris', 'Nilgiris', 'Non-Autonomous', 147.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Engineering College of Nilgiris', 'Nilgiris', 'Non-Autonomous', 94.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa City Engineering College of Nilgiris', 'Nilgiris', 'Non-Autonomous', 130.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Regional College of Engineering of Nilgiris', 'Nilgiris', 'Government', 155.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Regional Institute of Technology of Nilgiris', 'Nilgiris', 'Autonomous', 112.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Regional Institute of Technology of Nilgiris', 'Nilgiris', 'Non-Autonomous', 175.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer College of Engineering of Nilgiris', 'Nilgiris', 'Non-Autonomous', 148.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita College of Engineering of Nilgiris', 'Nilgiris', 'Non-Autonomous', 144.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa City Engineering College of Nilgiris', 'Nilgiris', 'Non-Autonomous', 175.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer Regional Institute of Science and Technology of Nilgiris', 'Nilgiris', 'Non-Autonomous', 112.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita City Institute of Technology of Nilgiris', 'Nilgiris', 'Government-Aided', 178.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath City Engineering College of Nilgiris', 'Nilgiris', 'Autonomous', 121.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer College of Engineering of Nilgiris', 'Nilgiris', 'Government', 164.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Institute of Technology of Nilgiris', 'Nilgiris', 'Non-Autonomous', 111.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global City Institute of Technology of Perambalur', 'Perambalur', 'Non-Autonomous', 109.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global City Engineering College of Perambalur', 'Perambalur', 'Autonomous', 130.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS College of Engineering of Perambalur', 'Perambalur', 'Non-Autonomous', 96.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha City Institute of Science and Technology of Perambalur', 'Perambalur', 'Non-Autonomous', 195.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National Regional Engineering College of Perambalur', 'Perambalur', 'Non-Autonomous', 194.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa Regional Engineering College of Perambalur', 'Perambalur', 'Government', 109.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal City Engineering College of Perambalur', 'Perambalur', 'Government-Aided', 119.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa Institute of Technology of Perambalur', 'Perambalur', 'Non-Autonomous', 137.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Institute of Technology of Perambalur', 'Perambalur', 'Autonomous', 197.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita City College of Engineering of Perambalur', 'Perambalur', 'Non-Autonomous', 121.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Engineering College of Perambalur', 'Perambalur', 'Non-Autonomous', 97.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS City Engineering College of Perambalur', 'Perambalur', 'Non-Autonomous', 100.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National Institute of Technology of Pudukkottai', 'Pudukkottai', 'Non-Autonomous', 137.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Engineering College of Pudukkottai', 'Pudukkottai', 'Government-Aided', 122.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Regional Institute of Technology of Pudukkottai', 'Pudukkottai', 'Non-Autonomous', 181.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Institute of Technology of Pudukkottai', 'Pudukkottai', 'Non-Autonomous', 110.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City Institute of Science and Technology of Pudukkottai', 'Pudukkottai', 'Non-Autonomous', 129.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Regional College of Engineering of Pudukkottai', 'Pudukkottai', 'Non-Autonomous', 106.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Engineering College of Pudukkottai', 'Pudukkottai', 'Non-Autonomous', 190.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal City Institute of Technology of Pudukkottai', 'Pudukkottai', 'Autonomous', 110.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Regional College of Engineering of Pudukkottai', 'Pudukkottai', 'Non-Autonomous', 166.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna Regional Engineering College of Pudukkottai', 'Pudukkottai', 'Non-Autonomous', 115.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Institute of Science and Technology of Ramanathapuram', 'Ramanathapuram', 'Autonomous', 132.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam City Institute of Technology of Ramanathapuram', 'Ramanathapuram', 'Non-Autonomous', 163.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Engineering College of Ramanathapuram', 'Ramanathapuram', 'Non-Autonomous', 153.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Engineering College of Ramanathapuram', 'Ramanathapuram', 'Non-Autonomous', 163.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City Institute of Technology of Ramanathapuram', 'Ramanathapuram', 'Government-Aided', 125.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS Regional College of Engineering of Ramanathapuram', 'Ramanathapuram', 'Non-Autonomous', 124.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha City Engineering College of Ramanathapuram', 'Ramanathapuram', 'Non-Autonomous', 176.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS Institute of Technology of Ramanathapuram', 'Ramanathapuram', 'Non-Autonomous', 155.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Institute of Science and Technology of Ramanathapuram', 'Ramanathapuram', 'Non-Autonomous', 123.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri City Engineering College of Ramanathapuram', 'Ramanathapuram', 'Autonomous', 111.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Engineering College of Ramanathapuram', 'Ramanathapuram', 'Non-Autonomous', 127.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj Regional Institute of Science and Technology of Ramanathapuram', 'Ramanathapuram', 'Autonomous', 152.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Regional Institute of Science and Technology of Ramanathapuram', 'Ramanathapuram', 'Autonomous', 99.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City Institute of Technology of Ramanathapuram', 'Ramanathapuram', 'Autonomous', 102.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal City Institute of Technology of Ramanathapuram', 'Ramanathapuram', 'Non-Autonomous', 193.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal City Engineering College of Ranipet', 'Ranipet', 'Non-Autonomous', 191.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar City Institute of Technology of Ranipet', 'Ranipet', 'Government-Aided', 151.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Institute of Technology of Ranipet', 'Ranipet', 'Non-Autonomous', 166.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna Engineering College of Ranipet', 'Ranipet', 'Non-Autonomous', 93.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer City Institute of Science and Technology of Ranipet', 'Ranipet', 'Non-Autonomous', 100.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS Regional Engineering College of Ranipet', 'Ranipet', 'Non-Autonomous', 185.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Engineering College of Ranipet', 'Ranipet', 'Non-Autonomous', 126.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Regional College of Engineering of Ranipet', 'Ranipet', 'Non-Autonomous', 111.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj City Institute of Technology of Ranipet', 'Ranipet', 'Autonomous', 118.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri City Institute of Technology of Ranipet', 'Ranipet', 'Non-Autonomous', 170.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS Regional College of Engineering of Salem', 'Salem', 'Non-Autonomous', 159.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa City College of Engineering of Salem', 'Salem', 'Non-Autonomous', 95.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Engineering College of Salem', 'Salem', 'Non-Autonomous', 131.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Institute of Science and Technology of Salem', 'Salem', 'Non-Autonomous', 165.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna City Engineering College of Salem', 'Salem', 'Non-Autonomous', 105.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal City Engineering College of Salem', 'Salem', 'Non-Autonomous', 137.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Engineering College of Salem', 'Salem', 'Non-Autonomous', 143.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha City Institute of Technology of Salem', 'Salem', 'Non-Autonomous', 130.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer Engineering College of Salem', 'Salem', 'Non-Autonomous', 195.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa City Institute of Science and Technology of Salem', 'Salem', 'Non-Autonomous', 143.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Engineering College of Salem', 'Salem', 'Non-Autonomous', 175.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Regional College of Engineering of Salem', 'Salem', 'Non-Autonomous', 190.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer Regional Institute of Science and Technology of Salem', 'Salem', 'Non-Autonomous', 176.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal City Institute of Technology of Sivaganga', 'Sivaganga', 'Non-Autonomous', 141.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City College of Engineering of Sivaganga', 'Sivaganga', 'Non-Autonomous', 130.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City College of Engineering of Sivaganga', 'Sivaganga', 'Government-Aided', 167.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer City Institute of Science and Technology of Sivaganga', 'Sivaganga', 'Government', 146.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Regional Institute of Science and Technology of Sivaganga', 'Sivaganga', 'Autonomous', 102.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Institute of Technology of Sivaganga', 'Sivaganga', 'Non-Autonomous', 150.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Engineering College of Sivaganga', 'Sivaganga', 'Non-Autonomous', 192.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna College of Engineering of Sivaganga', 'Sivaganga', 'Autonomous', 92.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna City Institute of Science and Technology of Sivaganga', 'Sivaganga', 'Autonomous', 113.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita City College of Engineering of Sivaganga', 'Sivaganga', 'Non-Autonomous', 114.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal City Institute of Science and Technology of Sivaganga', 'Sivaganga', 'Non-Autonomous', 118.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Institute of Science and Technology of Sivaganga', 'Sivaganga', 'Non-Autonomous', 166.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Regional Institute of Science and Technology of Sivaganga', 'Sivaganga', 'Non-Autonomous', 174.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj City Engineering College of Sivaganga', 'Sivaganga', 'Autonomous', 178.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam City College of Engineering of Tenkasi', 'Tenkasi', 'Non-Autonomous', 128.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar City Institute of Science and Technology of Tenkasi', 'Tenkasi', 'Non-Autonomous', 184.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City College of Engineering of Tenkasi', 'Tenkasi', 'Non-Autonomous', 127.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City College of Engineering of Tenkasi', 'Tenkasi', 'Non-Autonomous', 93.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS Institute of Science and Technology of Tenkasi', 'Tenkasi', 'Autonomous', 171.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Engineering College of Tenkasi', 'Tenkasi', 'Autonomous', 150.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar City Institute of Science and Technology of Tenkasi', 'Tenkasi', 'Non-Autonomous', 97.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Institute of Technology of Tenkasi', 'Tenkasi', 'Non-Autonomous', 164.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath City Engineering College of Tenkasi', 'Tenkasi', 'Autonomous', 117.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath City Institute of Technology of Tenkasi', 'Tenkasi', 'Government-Aided', 126.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Engineering College of Tenkasi', 'Tenkasi', 'Non-Autonomous', 128.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan Regional Engineering College of Tenkasi', 'Tenkasi', 'Non-Autonomous', 154.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS Regional Institute of Science and Technology of Thanjavur', 'Thanjavur', 'Autonomous', 123.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Engineering College of Thanjavur', 'Thanjavur', 'Non-Autonomous', 107.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Institute of Technology of Thanjavur', 'Thanjavur', 'Non-Autonomous', 146.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City Institute of Science and Technology of Thanjavur', 'Thanjavur', 'Non-Autonomous', 106.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar City Engineering College of Thanjavur', 'Thanjavur', 'Non-Autonomous', 162.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS Regional College of Engineering of Thanjavur', 'Thanjavur', 'Non-Autonomous', 186.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam Regional Institute of Science and Technology of Thanjavur', 'Thanjavur', 'Non-Autonomous', 170.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Institute of Science and Technology of Thanjavur', 'Thanjavur', 'Government', 135.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj City Institute of Science and Technology of Thanjavur', 'Thanjavur', 'Non-Autonomous', 120.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal College of Engineering of Thanjavur', 'Thanjavur', 'Non-Autonomous', 153.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa Institute of Technology of Thanjavur', 'Thanjavur', 'Non-Autonomous', 117.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National Institute of Technology of Theni', 'Theni', 'Autonomous', 100.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global Institute of Science and Technology of Theni', 'Theni', 'Non-Autonomous', 187.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Institute of Technology of Theni', 'Theni', 'Autonomous', 198.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna Institute of Technology of Theni', 'Theni', 'Government-Aided', 109.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global City Institute of Science and Technology of Theni', 'Theni', 'Government-Aided', 196.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City Institute of Science and Technology of Theni', 'Theni', 'Autonomous', 114.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Regional Institute of Technology of Theni', 'Theni', 'Non-Autonomous', 154.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Engineering College of Theni', 'Theni', 'Non-Autonomous', 134.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar City College of Engineering of Theni', 'Theni', 'Autonomous', 178.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna City Institute of Technology of Theni', 'Theni', 'Non-Autonomous', 150.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City Institute of Technology of Theni', 'Theni', 'Non-Autonomous', 100.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath City Institute of Science and Technology of Theni', 'Theni', 'Non-Autonomous', 151.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel Institute of Technology of Thoothukudi', 'Thoothukudi', 'Non-Autonomous', 133.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha City College of Engineering of Thoothukudi', 'Thoothukudi', 'Non-Autonomous', 120.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer City Institute of Technology of Thoothukudi', 'Thoothukudi', 'Non-Autonomous', 166.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Institute of Technology of Thoothukudi', 'Thoothukudi', 'Non-Autonomous', 189.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Institute of Science and Technology of Thoothukudi', 'Thoothukudi', 'Autonomous', 179.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal City Institute of Science and Technology of Thoothukudi', 'Thoothukudi', 'Non-Autonomous', 171.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global College of Engineering of Thoothukudi', 'Thoothukudi', 'Non-Autonomous', 151.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Institute of Technology of Thoothukudi', 'Thoothukudi', 'Non-Autonomous', 102.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National City Engineering College of Thoothukudi', 'Thoothukudi', 'Government-Aided', 180.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa City Institute of Science and Technology of Thoothukudi', 'Thoothukudi', 'Non-Autonomous', 174.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Institute of Science and Technology of Thoothukudi', 'Thoothukudi', 'Non-Autonomous', 143.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Regional Engineering College of Thoothukudi', 'Thoothukudi', 'Non-Autonomous', 112.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Regional Engineering College of Thoothukudi', 'Thoothukudi', 'Autonomous', 150.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar Regional College of Engineering of Thoothukudi', 'Thoothukudi', 'Non-Autonomous', 175.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar College of Engineering of Tiruchirappalli', 'Tiruchirappalli', 'Non-Autonomous', 132.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam City Engineering College of Tiruchirappalli', 'Tiruchirappalli', 'Non-Autonomous', 189.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National City Engineering College of Tiruchirappalli', 'Tiruchirappalli', 'Non-Autonomous', 110.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj City Engineering College of Tiruchirappalli', 'Tiruchirappalli', 'Non-Autonomous', 116.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City Institute of Science and Technology of Tiruchirappalli', 'Tiruchirappalli', 'Non-Autonomous', 175.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global Institute of Technology of Tiruchirappalli', 'Tiruchirappalli', 'Non-Autonomous', 152.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri City Engineering College of Tiruchirappalli', 'Tiruchirappalli', 'Autonomous', 125.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City College of Engineering of Tiruchirappalli', 'Tiruchirappalli', 'Autonomous', 168.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer Engineering College of Tiruchirappalli', 'Tiruchirappalli', 'Government-Aided', 168.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj Regional Institute of Science and Technology of Tiruchirappalli', 'Tiruchirappalli', 'Non-Autonomous', 179.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Institute of Science and Technology of Tiruchirappalli', 'Tiruchirappalli', 'Government', 166.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global Regional College of Engineering of Tiruchirappalli', 'Tiruchirappalli', 'Non-Autonomous', 100.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City Institute of Science and Technology of Tiruchirappalli', 'Tiruchirappalli', 'Autonomous', 106.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Engineering College of Tirunelveli', 'Tirunelveli', 'Government', 176.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS Engineering College of Tirunelveli', 'Tirunelveli', 'Non-Autonomous', 176.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS Regional College of Engineering of Tirunelveli', 'Tirunelveli', 'Government', 127.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City College of Engineering of Tirunelveli', 'Tirunelveli', 'Autonomous', 171.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Institute of Science and Technology of Tirunelveli', 'Tirunelveli', 'Autonomous', 91.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS College of Engineering of Tirunelveli', 'Tirunelveli', 'Autonomous', 165.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Institute of Science and Technology of Tirunelveli', 'Tirunelveli', 'Non-Autonomous', 103.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Institute of Science and Technology of Tirunelveli', 'Tirunelveli', 'Non-Autonomous', 183.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar Regional Institute of Technology of Tirunelveli', 'Tirunelveli', 'Non-Autonomous', 189.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj Engineering College of Tirunelveli', 'Tirunelveli', 'Autonomous', 126.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS Regional College of Engineering of Tirupattur', 'Tirupattur', 'Autonomous', 182.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal City Institute of Science and Technology of Tirupattur', 'Tirupattur', 'Non-Autonomous', 91.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National City Institute of Science and Technology of Tirupattur', 'Tirupattur', 'Non-Autonomous', 172.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS Regional College of Engineering of Tirupattur', 'Tirupattur', 'Non-Autonomous', 171.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City College of Engineering of Tirupattur', 'Tirupattur', 'Autonomous', 98.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath City Institute of Science and Technology of Tirupattur', 'Tirupattur', 'Non-Autonomous', 99.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS Regional Engineering College of Tirupattur', 'Tirupattur', 'Government', 171.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global College of Engineering of Tirupattur', 'Tirupattur', 'Autonomous', 188.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City College of Engineering of Tirupattur', 'Tirupattur', 'Non-Autonomous', 147.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global Engineering College of Tirupattur', 'Tirupattur', 'Non-Autonomous', 108.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam College of Engineering of Tirupattur', 'Tirupattur', 'Autonomous', 103.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna Regional Institute of Technology of Tiruppur', 'Tiruppur', 'Government', 122.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City College of Engineering of Tiruppur', 'Tiruppur', 'Non-Autonomous', 180.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Engineering College of Tiruppur', 'Tiruppur', 'Non-Autonomous', 155.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam City Institute of Science and Technology of Tiruppur', 'Tiruppur', 'Non-Autonomous', 99.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa Regional Institute of Technology of Tiruppur', 'Tiruppur', 'Non-Autonomous', 109.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS City College of Engineering of Tiruppur', 'Tiruppur', 'Non-Autonomous', 122.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal College of Engineering of Tiruppur', 'Tiruppur', 'Autonomous', 190.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global Regional College of Engineering of Tiruppur', 'Tiruppur', 'Autonomous', 155.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City College of Engineering of Tiruppur', 'Tiruppur', 'Non-Autonomous', 162.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National City College of Engineering of Tiruppur', 'Tiruppur', 'Non-Autonomous', 103.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City Engineering College of Tiruvallur', 'Tiruvallur', 'Government', 171.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Institute of Science and Technology of Tiruvallur', 'Tiruvallur', 'Autonomous', 138.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Institute of Science and Technology of Tiruvallur', 'Tiruvallur', 'Non-Autonomous', 128.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam Regional College of Engineering of Tiruvallur', 'Tiruvallur', 'Non-Autonomous', 116.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel Regional College of Engineering of Tiruvallur', 'Tiruvallur', 'Autonomous', 183.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam Regional Institute of Science and Technology of Tiruvallur', 'Tiruvallur', 'Non-Autonomous', 108.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam College of Engineering of Tiruvallur', 'Tiruvallur', 'Non-Autonomous', 176.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri City Institute of Science and Technology of Tiruvallur', 'Tiruvallur', 'Government-Aided', 173.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global City College of Engineering of Tiruvallur', 'Tiruvallur', 'Autonomous', 117.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal City Engineering College of Tiruvallur', 'Tiruvallur', 'Non-Autonomous', 91.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Regional Institute of Science and Technology of Tiruvannamalai', 'Tiruvannamalai', 'Non-Autonomous', 109.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Jayam City College of Engineering of Tiruvannamalai', 'Tiruvannamalai', 'Non-Autonomous', 141.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National City Engineering College of Tiruvannamalai', 'Tiruvannamalai', 'Autonomous', 158.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer City Engineering College of Tiruvannamalai', 'Tiruvannamalai', 'Non-Autonomous', 140.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Engineering College of Tiruvannamalai', 'Tiruvannamalai', 'Non-Autonomous', 154.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Karpagam Regional College of Engineering of Tiruvannamalai', 'Tiruvannamalai', 'Autonomous', 102.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS Regional College of Engineering of Tiruvannamalai', 'Tiruvannamalai', 'Non-Autonomous', 171.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj City Institute of Technology of Tiruvannamalai', 'Tiruvannamalai', 'Government-Aided', 104.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National Institute of Technology of Tiruvannamalai', 'Tiruvannamalai', 'Non-Autonomous', 100.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS Regional Institute of Technology of Tiruvannamalai', 'Tiruvannamalai', 'Autonomous', 189.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam Regional Engineering College of Tiruvannamalai', 'Tiruvannamalai', 'Non-Autonomous', 133.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Institute of Science and Technology of Tiruvannamalai', 'Tiruvannamalai', 'Non-Autonomous', 183.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna City Engineering College of Tiruvannamalai', 'Tiruvannamalai', 'Autonomous', 133.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan Institute of Technology of Tiruvannamalai', 'Tiruvannamalai', 'Non-Autonomous', 158.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Regional College of Engineering of Tiruvannamalai', 'Tiruvannamalai', 'Non-Autonomous', 143.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj Regional Engineering College of Tiruvarur', 'Tiruvarur', 'Autonomous', 163.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa Institute of Science and Technology of Tiruvarur', 'Tiruvarur', 'Autonomous', 193.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel Regional Institute of Science and Technology of Tiruvarur', 'Tiruvarur', 'Autonomous', 146.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City College of Engineering of Tiruvarur', 'Tiruvarur', 'Non-Autonomous', 176.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Anna College of Engineering of Tiruvarur', 'Tiruvarur', 'Autonomous', 135.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita Regional College of Engineering of Tiruvarur', 'Tiruvarur', 'Non-Autonomous', 140.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj City Institute of Science and Technology of Tiruvarur', 'Tiruvarur', 'Non-Autonomous', 136.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS City Engineering College of Tiruvarur', 'Tiruvarur', 'Non-Autonomous', 112.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam College of Engineering of Tiruvarur', 'Tiruvarur', 'Autonomous', 176.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City College of Engineering of Tiruvarur', 'Tiruvarur', 'Non-Autonomous', 186.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Institute of Technology of Tiruvarur', 'Tiruvarur', 'Non-Autonomous', 149.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National City Engineering College of Tiruvarur', 'Tiruvarur', 'Autonomous', 100.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer Institute of Technology of Tiruvarur', 'Tiruvarur', 'Autonomous', 154.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar City Institute of Technology of Tiruvarur', 'Tiruvarur', 'Non-Autonomous', 193.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha City Engineering College of Vellore', 'Vellore', 'Non-Autonomous', 185.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Vellalar City Engineering College of Vellore', 'Vellore', 'Non-Autonomous', 173.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Dr. Kalam City College of Engineering of Vellore', 'Vellore', 'Non-Autonomous', 130.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar City Institute of Technology of Vellore', 'Vellore', 'Non-Autonomous', 173.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Regional Institute of Technology of Vellore', 'Vellore', 'Non-Autonomous', 151.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Pioneer City College of Engineering of Vellore', 'Vellore', 'Autonomous', 159.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Engineering College of Vellore', 'Vellore', 'Autonomous', 97.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Institute of Science and Technology of Vellore', 'Vellore', 'Autonomous', 117.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj Institute of Science and Technology of Vellore', 'Vellore', 'Non-Autonomous', 184.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath Institute of Science and Technology of Vellore', 'Vellore', 'Non-Autonomous', 141.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global City College of Engineering of Vellore', 'Vellore', 'Non-Autonomous', 91.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Institute of Technology of Viluppuram', 'Viluppuram', 'Autonomous', 93.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan Institute of Technology of Viluppuram', 'Viluppuram', 'Non-Autonomous', 129.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan City Institute of Science and Technology of Viluppuram', 'Viluppuram', 'Non-Autonomous', 195.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City Engineering College of Viluppuram', 'Viluppuram', 'Autonomous', 141.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Mother Teresa City Engineering College of Viluppuram', 'Viluppuram', 'Non-Autonomous', 123.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar City Institute of Science and Technology of Viluppuram', 'Viluppuram', 'Government', 126.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('National City Engineering College of Viluppuram', 'Viluppuram', 'Non-Autonomous', 152.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kalaignar City Institute of Science and Technology of Viluppuram', 'Viluppuram', 'Non-Autonomous', 111.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal City Engineering College of Viluppuram', 'Viluppuram', 'Non-Autonomous', 107.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('SNS Regional Institute of Science and Technology of Viluppuram', 'Viluppuram', 'Non-Autonomous', 141.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('RVS City College of Engineering of Viluppuram', 'Viluppuram', 'Non-Autonomous', 113.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Global Regional Engineering College of Virudhunagar', 'Virudhunagar', 'Non-Autonomous', 149.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Sri Institute of Science and Technology of Virudhunagar', 'Virudhunagar', 'Non-Autonomous', 109.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('CVS College of Engineering of Virudhunagar', 'Virudhunagar', 'Autonomous', 173.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal Engineering College of Virudhunagar', 'Virudhunagar', 'Non-Autonomous', 196.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Hindusthan Engineering College of Virudhunagar', 'Virudhunagar', 'Autonomous', 109.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel City Engineering College of Virudhunagar', 'Virudhunagar', 'Non-Autonomous', 140.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha Regional College of Engineering of Virudhunagar', 'Virudhunagar', 'Non-Autonomous', 118.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Excel Regional Institute of Technology of Virudhunagar', 'Virudhunagar', 'Autonomous', 110.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Muthayammal Regional Engineering College of Virudhunagar', 'Virudhunagar', 'Non-Autonomous', 117.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Kamaraj City Institute of Technology of Virudhunagar', 'Virudhunagar', 'Government-Aided', 135.00);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Amrita City Engineering College of Virudhunagar', 'Virudhunagar', 'Non-Autonomous', 117.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Maha Engineering College of Virudhunagar', 'Virudhunagar', 'Government-Aided', 107.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Bharath City College of Engineering of Virudhunagar', 'Virudhunagar', 'Non-Autonomous', 147.50);
INSERT INTO college (name, district, type, previous_year_cutoff) VALUES ('Royal City Institute of Science and Technology of Virudhunagar', 'Virudhunagar', 'Non-Autonomous', 192.00);
